# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df2aabacd82bf2db4e9dd17dd15d830c128b0d9cb84ba02214f922889b91332639b42a625eb2d7ea8bfb54b34c9f4776707d310af3897caf55c9f8b605eac6e9

test:
  secret_key_base: eaf33f2643317c664312a4d7c68523800eda5479907df3f6991a7d6d46448676b7be76cfd3698ab60bb58b74afd26285eff9cd0e060da125aa0648d354252ee9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
