# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1864b4ecc89610837f699167f266654d7191e01acc9bd07a11781682cfc371db04d4d7eb9dc803321321c6376dd78a32977cb9a0427c9486d81ae98a35c03d74

test:
  secret_key_base: 1e79b24e426b43b8cbfda19709e38c4d092b392c65f655e42fbc0cac1672bf831a08b6201d0ee845147e4f764d5f45c4faa3ba1f409307c4b3e26b74b2a14fd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
